language: python
cache:
    directories:
        - "~/.platformio"
python:
    - "2.7"
install:
    - pip install -U platformio
    - platformio update
    - platformio lib -g install 63 1477 79 44 1262 64
    
script:
    - platformio run
